name: Binary Release

on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64, windows/amd64, darwin/amd64
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2

    - name: Set APP_VERSION env
      run: |
        echo "APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev )" >> $GITHUB_E

    - name: Set BUILD_TIME env
      run: |
        echo "BUILD_TIME=$(date)" >> $GITHUB_ENV

    - uses: wangyoucao577/go-release-action@master
      name: run the build
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
